#!/bin/sh
   echo $USER
sudo -i <<EOF
    echo $USER
    cd /var/projects/jenkins-demo/node-app
    echo $USER
    git pull origin master
    npm i
    echo $USER
    forever start -a --uid node-app index.js
    forever list
    exit
   echo $USER
EOF
