#!/bin/sh
ssh ubuntu@3.224.206.123 <<EOF
    cd ~/node-app
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon forever
    forever stop node-app
    forever start -a --uid node-app index.js
    exit
EOF
